- name: Install yum-packages common
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gimp
    - flameshot
    - inkscape
    - vim
    - podman-compose
    - lastpass-cli
    - lastpass-cli
    - dl
    - mercurial
    - ImageMagick
    - golang
  tags:
    - common

