- name: Install yum-packages common
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dl
    - flameshot
    - gimp
    - golang
    - ImageMagick
    - inkscape
    - lastpass-cli
    - lastpass-cli
    - mercurial
    - pandoc
    - podman-compose
    - vim
  tags:
    - common

